backend:
  name: git-gateway
  branch: master

# Adds an interface for drafting, reviewing, and approving posts
publish_mode: editorial_workflow

# Media files will be stored in the repo under static/images/uploads
media_folder: 'static/images/uploads'

# The src attribute for uploaded media will begin with /images/uploads
public_folder: '/images/uploads'

# Collections define the structure for the different content types
collections:
  - name: 'project' # Used in routes, e.g., /admin/collections/stories
    label: 'Project' # Used in the UI
    folder: 'src/projects' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., about.md
    fields: # The fields for each document, usually in front matter
      - {
          label: 'Title',
          name: 'title',
          widget: 'string',
          hint: 'Friendly top-level heading on the page and meta title within the browser',
        }
      - {
          label: 'Slug',
          name: 'slug',
          widget: 'string',
          hint: 'Unique url to access this content',
        }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          'Timestamp representing when this content was `published`',
        }
      - {
          label: 'Banner',
          name: 'banner',
          widget: 'image',
          hint: 'Shown at top of the detail page',
        }
      - {
          label: 'Preview Image',
          name: 'previewImage',
          widget: 'image',
          hint: 'Will be rendered in a square element on the list page',
        }
      - {
          label: 'Excerpt',
          name: 'excerpt',
          widget: 'string',
          hint: 'Short summary to show in the project list',
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
          label: 'Featured',
          name: 'featured',
          widget: 'boolean',
          hint: 'If true, will appear on the homepage',
        }
      - {
          label: 'Gallery',
          name: 'gallery',
          widget: "list",
          field: { label: Image, name: image, widget: image },
          hint: 'List of images that appear at the bottom of the detail page'
        }
